#!/usr/bin/env python3
"""
TLL OS Code Runtime

Safe code execution environment for TLL OS.
"""

import time
from typing import Dict, Optional
from dataclasses import dataclass, field


@dataclass
class CodeExecutionResult:
    """Code execution result."""
    code: str
    output: str
    success: bool
    error: Optional[str] = None
    execution_time_ms: float = 0.0
    lines_of_code: int = 0


class TLLCodeRuntime:
    """TLL OS Code Runtime - safe code generation and execution."""

    def __init__(self, process_manager=None):
        self.process_manager = process_manager
        self.execution_history: list = []
        self.generated_code: list = []

    def generate_code(self, description: str, language: str = "python") -> Dict:
        """Generate code based on description (template-based)."""
        templates = {
            "hello": f"""# Generated by TLL Agent
# Description: {description}
print("Hello, TLL OS!")
""",
            "window": f"""# Generated by TLL Agent
# Description: {description}
def create_window():
    return {{"title": "New Window", "size": "400x300"}}
""",
            "default": f"""# Generated by TLL Agent
# Description: {description}
# TODO: Implement logic
result = {{"status": "ok"}}
"""
        }

        # Simple template selection based on keywords
        if "hello" in description.lower():
            code = templates["hello"]
        elif "window" in description.lower():
            code = templates["window"]
        else:
            code = templates["default"]

        self.generated_code.append({
            "description": description,
            "code": code,
            "language": language,
            "timestamp": time.time()
        })

        return {
            "description": description,
            "code": code,
            "language": language,
            "lines": len(code.split("\n"))
        }

    def run_code(self, code: str) -> CodeExecutionResult:
        """Run code in safe sandbox (limited execution)."""
        start = time.time()

        # Very limited execution - just count lines and return output
        lines = code.strip().split("\n")
        line_count = len(lines)

        # Extract print statements for "output"
        output_lines = []
        for line in lines:
            if "print(" in line:
                # Extract content inside print()
                start_idx = line.find('print(') + 6
                end_idx = line.rfind(')')
                if start_idx < end_idx:
                    content = line[start_idx:end_idx].strip('"\'')
                    output_lines.append(content)

        execution_time = (time.time() - start) * 1000

        result = CodeExecutionResult(
            code=code,
            output="\n".join(output_lines) if output_lines else "[execution complete]",
            success=True,
            execution_time_ms=round(execution_time, 2),
            lines_of_code=line_count
        )

        self.execution_history.append(result)
        return result

    def get_stats(self) -> Dict:
        """Get code runtime statistics."""
        return {
            "total_generated": len(self.generated_code),
            "total_executions": len(self.execution_history),
            "total_lines_executed": sum(r.lines_of_code for r in self.execution_history)
        }
