#!/usr/bin/env pwsh
# TLL Cross-Target Conformance Test Framework
# 同一份 TLL 源码 → Bytecode 与 Native 两条真实编译路径 → 自动比较输出和退出码
#
# Usage:
#   scripts/cross-target-conformance.ps1 [test_file.tll]
#
# Default test: tests/native/cross_target_minimal.tll
#
# Exit codes:
#   0 = PASS (stdout and exit code identical)
#   1 = FAIL (differences detected or build error)

param(
    [string]$TestFile = "tests/native/cross_target_minimal.tll"
)

$ErrorActionPreference = "Continue"
$REPO_ROOT = Split-Path -Parent $PSScriptRoot
$TLLVM = Join-Path $REPO_ROOT "host\c\tllvm.exe"
$TLLC_BC = Join-Path $REPO_ROOT "tools\TLLC\tllc.tllbc"
$NATIVE_DRIVER_BC = Join-Path $REPO_ROOT "compiler\native_compile_driver.tllbc"
$TEST_DIR = Split-Path -Parent (Join-Path $REPO_ROOT $TestFile)
$TEST_NAME = [System.IO.Path]::GetFileNameWithoutExtension($TestFile)
$BYTECODE_BC = Join-Path $TEST_DIR "$TEST_NAME.tllbc"
$NATIVE_C = Join-Path $TEST_DIR "$TEST_NAME.c"
$NATIVE_EXE = Join-Path $TEST_DIR "$TEST_NAME.exe"
$NATIVE_OUT = Join-Path $TEST_DIR "$TEST_NAME.native_out.txt"
$BYTECODE_OUT = Join-Path $TEST_DIR "$TEST_NAME.bytecode_out.txt"
$EVIDENCE_FILE = Join-Path $TEST_DIR "$TEST_NAME.evidence.txt"

# 清理旧产物
if (Test-Path $BYTECODE_BC) { Remove-Item $BYTECODE_BC -Force }
if (Test-Path $NATIVE_C) { Remove-Item $NATIVE_C -Force }
if (Test-Path $NATIVE_EXE) { Remove-Item $NATIVE_EXE -Force }

function Write-Evidence {
    param(
        [string]$BcCompile = "FAIL",
        [string]$NtLower = "FAIL",
        [string]$NtCompile = "FAIL",
        [int]$BcExit = -1,
        [int]$NtExit = -1,
        [bool]$StdoutSame = $false,
        [bool]$ExitSame = $false,
        [string]$Overall = "FAIL"
    )
    $lines = @()
    $lines += "TLL Cross-Target Conformance Evidence"
    $lines += "================================"
    $lines += "Test file: $TestFile"
    $lines += "Timestamp: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    $lines += ""
    $lines += "Build Status:"
    $lines += "  Bytecode compile: $BcCompile"
    $lines += "  Native lower:     $NtLower"
    $lines += "  Native compile:   $NtCompile"
    $lines += ""
    $lines += "Execution:"
    $lines += "  Bytecode exit code: $BcExit"
    $lines += "  Native exit code:   $NtExit"
    $lines += "  Exit code identical: $ExitSame"
    $lines += ""
    $lines += "Output Comparison:"
    $lines += "  stdout identical: $StdoutSame"
    if (Test-Path $BYTECODE_OUT) {
        $bcLines = (Get-Content $BYTECODE_OUT).Count
        $lines += "  Bytecode stdout lines: $bcLines"
    }
    if (Test-Path $NATIVE_OUT) {
        $ntLines = (Get-Content $NATIVE_OUT).Count
        $lines += "  Native stdout lines:   $ntLines"
    }
    $lines += ""
    $lines += "Overall: $Overall"
    $lines | Out-File $EVIDENCE_FILE -Encoding utf8
}

Write-Output "============================================================"
Write-Output "TLL Cross-Target Conformance Test"
Write-Output "Test file: $TestFile"
Write-Output "============================================================"
Write-Output ""

# ============================================================
# Step 1: Bytecode compile
# ============================================================
Write-Output "[1/6] Bytecode compile (tllc.tllbc)..."
Push-Location $REPO_ROOT
& $TLLVM $TLLC_BC compile $TestFile $BYTECODE_BC 2>&1 | Out-Null
$bcCompileExit = $LASTEXITCODE
Pop-Location

if ($bcCompileExit -ne 0 -or -not (Test-Path $BYTECODE_BC)) {
    Write-Output "  FAIL: Bytecode compile failed"
    Write-Evidence -BcCompile "FAIL" -Overall "FAIL"
    Write-Output "  CROSS-TARGET CONFORMANCE: FAIL"
    exit 1
}
Write-Output "  PASS: Bytecode compile successful"

# ============================================================
# Step 2: Native lower (native_lower.tll → C)
# ============================================================
Write-Output "[2/6] Native lower (native_lower.tll -> C)..."
Push-Location $REPO_ROOT
& $TLLVM $NATIVE_DRIVER_BC $TestFile $NATIVE_C 2>&1 | Out-Null
$ntLowerExit = $LASTEXITCODE
Pop-Location

if ($ntLowerExit -ne 0 -or -not (Test-Path $NATIVE_C)) {
    Write-Output "  FAIL: Native lower (C generation) failed"
    Write-Evidence -BcCompile "PASS" -NtLower "FAIL" -Overall "FAIL"
    Write-Output "  CROSS-TARGET CONFORMANCE: FAIL"
    exit 1
}
Write-Output "  PASS: Native lower successful (C generated by native_lower.tll, not handwritten)"

# ============================================================
# Step 3: Native compile (MSVC)
# ============================================================
Write-Output "[3/6] Native compile (MSVC)..."
$vcvars = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
Push-Location $REPO_ROOT
cmd /c "`"$vcvars`" x64 >nul 2>&1 && cl /nologo /O2 /utf-8 /I native\runtime /I runtime `"$NATIVE_C`" native\runtime\tll_native.c runtime\value.c runtime\arithmetic.c runtime\io.c /Fe:`"$NATIVE_EXE`"" 2>&1 | Out-Null
$msvcExit = $LASTEXITCODE
Pop-Location

if ($msvcExit -ne 0 -or -not (Test-Path $NATIVE_EXE)) {
    Write-Output "  FAIL: MSVC compile failed"
    Write-Evidence -BcCompile "PASS" -NtLower "PASS" -NtCompile "FAIL" -Overall "FAIL"
    Write-Output "  CROSS-TARGET CONFORMANCE: FAIL"
    exit 1
}
Write-Output "  PASS: MSVC compile successful (0 errors, 0 warnings)"

# ============================================================
# Step 4: Run Bytecode
# ============================================================
Write-Output "[4/6] Run Bytecode (tllvm)..."
& $TLLVM $BYTECODE_BC > $BYTECODE_OUT 2>&1
$bcExit = $LASTEXITCODE
Write-Output "  Exit code: $bcExit"

# ============================================================
# Step 5: Run Native
# ============================================================
Write-Output "[5/6] Run Native (native EXE)..."
& $NATIVE_EXE > $NATIVE_OUT 2>&1
$ntExit = $LASTEXITCODE
Write-Output "  Exit code: $ntExit"

# ============================================================
# Step 6: Compare
# ============================================================
Write-Output "[6/6] Compare outputs..."
Write-Output ""
Write-Output "--- Bytecode output ---"
Get-Content $BYTECODE_OUT
Write-Output "--- Native output ---"
Get-Content $NATIVE_OUT
Write-Output ""

$stdoutSame = $true
$diff = Compare-Object (Get-Content $BYTECODE_OUT) (Get-Content $NATIVE_OUT)
if ($diff -ne $null) {
    $stdoutSame = $false
    Write-Output "  STDOUT DIFFERENCES:"
    $diff | ForEach-Object { Write-Output "    $($_.SideIndicator): $($_.InputObject)" }
}

$exitSame = ($bcExit -eq $ntExit)
$overall = if ($stdoutSame -and $exitSame) { "PASS" } else { "FAIL" }

Write-Evidence -BcCompile "PASS" -NtLower "PASS" -NtCompile "PASS" `
    -BcExit $bcExit -NtExit $ntExit -StdoutSame $stdoutSame -ExitSame $exitSame -Overall $overall

Write-Output ""
Write-Output "============================================================"
Write-Output "CONFORMANCE RESULT"
Write-Output "============================================================"
Write-Output "  stdout identical:     $stdoutSame"
Write-Output "  exit code identical:  $exitSame"
Write-Output "  Bytecode exit:        $bcExit"
Write-Output "  Native exit:          $ntExit"
Write-Output "  Evidence file:        $EVIDENCE_FILE"
Write-Output ""

if ($overall -eq "PASS") {
    Write-Output "  CROSS-TARGET CONFORMANCE: PASS"
    exit 0
} else {
    Write-Output "  CROSS-TARGET CONFORMANCE: FAIL"
    exit 1
}
